global:
  scrape_interval: 5s

scrape_configs:
  - job_name: prf-api
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8000"]

  - job_name: containers
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: postgres
    static_configs:
      - targets: ["postgres-exporter:9187"]
